<?php

declare(strict_types=1);

namespace Toadbeatz\SwooleBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration definition for Swoole Bundle
 * Complete configuration for Symfony 7/8 with Swoole 6.1.4
 * 
 * @since Swoole 6.1
 * @compatible Symfony 7.0, 8.0
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('swoole');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                // HTTP Server Configuration
                ->arrayNode('http')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('host')->defaultValue('0.0.0.0')->end()
                        ->integerNode('port')->defaultValue(9501)->end()
                        ->arrayNode('options')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('open_http2_protocol')->defaultFalse()->end()
                                ->booleanNode('open_websocket_protocol')->defaultFalse()->end()
                                ->booleanNode('enable_static_handler')->defaultFalse()->end()
                                ->scalarNode('document_root')->defaultNull()->end()
                                ->arrayNode('static_handler_locations')
                                    ->prototype('scalar')->end()
                                    ->defaultValue(['/assets', '/bundles'])
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                // HTTPS Configuration
                ->arrayNode('https')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->integerNode('port')->defaultValue(9502)->end()
                        ->scalarNode('cert')->defaultNull()->end()
                        ->scalarNode('key')->defaultNull()->end()
                        ->scalarNode('ca')->defaultNull()->end()
                        ->booleanNode('verify_peer')->defaultFalse()->end()
                        ->integerNode('protocols')
                            ->defaultNull()
                            ->info('SSL/TLS protocols (default: TLSv1.2 | TLSv1.3)')
                        ->end()
                    ->end()
                ->end()

                // HTTP/2 Configuration
                ->arrayNode('http2')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('header_table_size')->defaultValue(4096)->end()
                        ->integerNode('initial_window_size')->defaultValue(65535)->end()
                        ->integerNode('max_concurrent_streams')->defaultValue(128)->end()
                        ->integerNode('max_frame_size')->defaultValue(16384)->end()
                        ->integerNode('max_header_list_size')->defaultValue(4096)->end()
                    ->end()
                ->end()

                // Hot Reload Configuration
                ->arrayNode('hot_reload')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->arrayNode('watch')
                            ->prototype('scalar')->end()
                            ->defaultValue(['src', 'config', 'templates'])
                        ->end()
                        ->integerNode('interval')
                            ->defaultValue(500)
                            ->info('Check interval in milliseconds')
                        ->end()
                    ->end()
                ->end()

                // Performance Configuration
                ->arrayNode('performance')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('worker_num')
                            ->defaultNull()
                            ->info('Number of worker processes (default: auto-detect CPU count)')
                        ->end()
                        ->integerNode('max_request')
                            ->defaultValue(10000)
                            ->info('Max requests per worker before restart')
                        ->end()
                        ->booleanNode('enable_coroutine')
                            ->defaultTrue()
                            ->info('Enable coroutine support')
                        ->end()
                        ->integerNode('max_coroutine')
                            ->defaultValue(100000)
                            ->info('Maximum number of coroutines')
                        ->end()
                        ->integerNode('coroutine_hook_flags')
                            ->defaultNull()
                            ->info('Coroutine hook flags (default: SWOOLE_HOOK_ALL)')
                        ->end()
                        ->integerNode('max_connection')
                            ->defaultValue(10000)
                            ->info('Maximum number of connections')
                        ->end()
                        ->integerNode('buffer_output_size')
                            ->defaultValue(33554432)
                            ->info('Output buffer size (32MB default)')
                        ->end()
                        ->integerNode('socket_buffer_size')
                            ->defaultValue(134217728)
                            ->info('Socket buffer size (128MB default)')
                        ->end()
                        ->integerNode('package_max_length')
                            ->defaultValue(10485760)
                            ->info('Maximum package length (10MB default)')
                        ->end()
                        ->booleanNode('enable_compression')
                            ->defaultTrue()
                            ->info('Enable HTTP compression')
                        ->end()
                        ->integerNode('compression_level')
                            ->defaultValue(3)
                            ->info('Compression level (1-9)')
                        ->end()
                        ->integerNode('compression_min_length')
                            ->defaultValue(20)
                            ->info('Minimum length for compression')
                        ->end()
                        ->booleanNode('websocket_compression')
                            ->defaultTrue()
                            ->info('Enable WebSocket compression')
                        ->end()
                        ->booleanNode('daemonize')
                            ->defaultFalse()
                            ->info('Run as daemon')
                        ->end()
                        ->integerNode('heartbeat_interval')
                            ->defaultValue(30)
                            ->info('Heartbeat check interval in seconds')
                        ->end()
                        ->integerNode('heartbeat_idle_time')
                            ->defaultValue(60)
                            ->info('Heartbeat idle timeout in seconds')
                        ->end()
                        ->booleanNode('enable_reuse_port')
                            ->defaultFalse()
                            ->info('Enable port reuse for multi-instance')
                        ->end()
                        ->booleanNode('thread_mode')
                            ->defaultFalse()
                            ->info('Enable Swoole 6.1 Thread mode (experimental)')
                        ->end()
                        ->booleanNode('base_mode')
                            ->defaultFalse()
                            ->info('Enable single-process base mode')
                        ->end()
                    ->end()
                ->end()

                // Debug Configuration
                ->arrayNode('debug')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->booleanNode('enable_dd')->defaultTrue()->end()
                        ->booleanNode('enable_var_dump')->defaultTrue()->end()
                    ->end()
                ->end()

                // Database Configuration
                ->arrayNode('database')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enable_pool')->defaultTrue()->end()
                        ->arrayNode('mysql')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('pool_size')->defaultValue(10)->end()
                                ->floatNode('timeout')->defaultValue(5.0)->end()
                            ->end()
                        ->end()
                        ->arrayNode('postgresql')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('pool_size')->defaultValue(10)->end()
                                ->floatNode('timeout')->defaultValue(5.0)->end()
                            ->end()
                        ->end()
                        ->arrayNode('redis')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('pool_size')->defaultValue(20)->end()
                                ->floatNode('timeout')->defaultValue(3.0)->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                // Task Workers Configuration
                ->arrayNode('task')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('worker_num')
                            ->defaultValue(2)
                            ->info('Number of task worker processes')
                        ->end()
                        ->integerNode('max_request')
                            ->defaultValue(10000)
                            ->info('Max tasks per task worker before restart')
                        ->end()
                    ->end()
                ->end()

                // Scheduler Configuration
                ->arrayNode('scheduler')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                    ->end()
                ->end()

                // Rate Limiter Configuration
                ->arrayNode('rate_limiter')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->integerNode('max_requests')->defaultValue(100)->end()
                        ->integerNode('window_seconds')->defaultValue(60)->end()
                    ->end()
                ->end()

                // Metrics Configuration
                ->arrayNode('metrics')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->integerNode('export_interval')->defaultValue(60)->end()
                    ->end()
                ->end()

                // Thread Pool Configuration (Swoole 6.1)
                ->arrayNode('thread_pool')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->integerNode('size')->defaultValue(4)->end()
                    ->end()
                ->end()

                // Process Pool Configuration
                ->arrayNode('process_pool')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->integerNode('size')->defaultValue(4)->end()
                    ->end()
                ->end()

                // WebSocket Configuration
                ->arrayNode('websocket')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->integerNode('max_frame_size')
                            ->defaultValue(65535)
                            ->info('Maximum WebSocket frame size')
                        ->end()
                        ->booleanNode('compression')
                            ->defaultTrue()
                            ->info('Enable WebSocket compression')
                        ->end()
                    ->end()
                ->end()

            ->end();

        return $treeBuilder;
    }
}
